### ISSUE TITLE
Migration reports check - remaining corrections to be done

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-migrator-kit#128]
**Comparison of migration reports with Library lists of recids**
- _Journals:_ list of record is identical on both sides
- _Proceedings_: 82 records not in the latest report but migrated at some point:
ex: https://cds.cern.ch/record/99763
https://sandbox-cds-ils.web.cern.ch/literature/n7zj1-y5688
- _Books_: some 20k records missing from the report, I checked a few of them and they seem to be migrated, so the issue seems to be with the report itself. But would be better to have the full report to double-check if there are missing records. 

**Corrections needed for journals:**
- **Fields to be ignored:** 
- [x] 690C:CERN
- [x] 710__5

**Corrections needed for proceedings AND Books:**
-  **Fields to be ignored:**
- [x] 905__ all subfields
- [x] 583__ all subfields
- **Rules not yet applied:**
- [x] 700__e:"et al." -> "contains other authors not listed" (https://github.com/CERNDocumentServer/cds-migrator-kit/issues/108)
- [x] Ignore 700$$e when value different than "ed.", "ed. et al.", "et al.", "et al", "ill." -> ignore  (https://github.com/CERNDocumentServer/cds-migrator-kit/issues/108)
- [x] 084__a and 084__2 as described in https://github.com/CERNDocumentServer/cds-migrator-kit/issues/108
- [x] Preprint should be in the list of material of identifiers https://github.com/CERNDocumentServer/cds-ils/issues/420
- [x] Ignore 710__5 https://github.com/CERNDocumentServer/cds-migrator-kit/issues/108
- [x] All other values in indicator 690C should be ignored  (PUBLLHCC, SCICOM, EUCARD, EUCARDBOO, INTNOTEALEPHPRIV, EuCARDCON, EGEEPUB, EGEETR, PUBLTCC..)
- [ ] Same for 980 when value is different than expected (SCICOMMPUBLLHCC, CMS_Reports, CLINOT...)
- [x] When author comes from 100 or 700 -> the author type is "Person"
- "**Audio CD"** is in the list of the identifiers material, why does it general an error?
Ex: 30.03.21 19:40 | 542 | 2285673 | None | WARNING | MARC: 340__ | INPUT VALUE: GroupableOrderedDict((('a' | 'Audio CD') | ('x' | 'CM-B00063186'))) ERROR: [UNEXPECTED INPUT VALUE]

- **Remaining migration errors, not easy to understand: :**
**Books:** 
30.03.21 22:58 | 408 | 1695879 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 878 | 1695884 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 555 | 1695886 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 101 | 1695902 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 799 | 1695904 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 490 | 1695912 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 699 | 1695913 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 381 | 1695915 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 589 | 1695916 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 189 | 1695920 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 387 | 1695922 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 73 | 1695929 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 279 | 1695932 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 485 | 1695938 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 690 | 1695939 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 895 | 1695941 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 564 | 1695944 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 766 | 1695945 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 972 | 1695946 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 602 | 1695948 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 213 | 1695952 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 431 | 1696073 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
30.03.21 22:58 | 300 | 1696105 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
31.03.21 04:41 | 757 | 1695901 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'lower'
**There is no field "250":** 
30.03.21 15:58 | 670 | 2706766 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 15:59 | 388 | 2706771 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:47 | 538 | 2706758 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:47 | 492 | 2706760 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:47 | 426 | 2706762 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:47 | 882 | 2706763 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:47 | 812 | 2706765 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 749 | 2706779 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 462 | 2706785 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 705 | 2706815 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 38 | 2706838 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 934 | 2706840 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 851 | 2706842 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 291 | 2706843 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 727 | 2706844 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
30.03.21 19:48 | 329 | 2706855 | None | WARNING | MARC: 250__ | INPUT VALUE: GroupableOrderedDict(()) ERROR: [UNEXPECTED INPUT VALUE](a)
**Proceedings:** 
30.03.21 17:22 | 79 | 602550 | None | ERROR | Impossible to convert to JSON 'NoneType' object has no attribute 'upper'
30.03.21 15:56 | 562 | 2746447 | None | ERROR | Impossible to convert to JSON invalid literal for int() with base 10: ''
30.03.21 16:59 | 393 | 2715524 | None | ERROR | Impossible to convert to JSON invalid literal for int() with base 10: ''
